language: csharp
solution: JT808.Protocol.sln
dotnet: 2.1.500
os: linux
mono: none
dist: trusty
script:
 - cd /src
 - dotnet restore JT808.Protocol.sln
 - dotnet build JT808.Protocol.Test/JT808.Protocol.Test.csproj
 - dotnet test JT808.Protocol.Test/JT808.Protocol.Test.csproj
after_success:
 - echo successful build!
branches:
  only:
    - master